### ISSUE TITLE
Packages and Script Changes to move to standards and get latest versions.

### ISSUE THREAD

**Issue by degnome** [IRVUI/twizzle-js#1]
Packages should be update to latest release if possible.
babel-core :  6.11.4
jsonwebtoken 7.1.7
mocha 3.0
supertest 2.0
web pack 1.13.1
adios 0.13.1

Move from should to Chai which is our standard test library we use.

Built code directory should change from build to list.

**Comment by karthikvdms** [comment]
@degnome Guess you meant dist there.

Pushed a PR. Please review and merge. Tnks.

**Comment by degnome** [comment]
Great will look

On Aug 4, 2016, at 12:07 PM, karthikvdms <notifications@github.com<mailto:notifications@github.com>> wrote:


@degnome<https://github.com/degnome> Guess you meant dist there.

Pushed a PR. Please review and merge. Tnks.
